library(ggplot2)
dir.create('results',showWarnings=FALSE)
clean<-function(path){d<-read.csv(path);d$employed<-d$S2401_C01_001E;d$tech<-d$S2401_C01_007E;d$tech_share<-100*d$tech/d$employed;d$unemployment<-d$S2301_C04_001E;d$epr<-d$S2301_C03_001E;stopifnot(all(is.finite(d$tech_share)),all(d$tech>0),all(d$tech<d$employed),all(d$unemployment>=0),all(d$epr>0));d}
d<-clean('data/state-panel.csv');bay<-clean('data/bay-panel.csv');stopifnot(nrow(d)==306,!anyDuplicated(d[c('year','state')]),all(table(d$year)==51),nrow(bay)==12);s<-subset(d,state!=11)
changes<-function(x,a,b,id='state'){z<-merge(subset(x,year==a),subset(x,year==b),by=id,suffixes=c('_start','_end'));z$tech_change<-z$tech_share_end-z$tech_share_start;z$unemployment_change<-z$unemployment_end-z$unemployment_start;z$epr_change<-z$epr_end-z$epr_start;z$tech_growth<-100*(z$tech_end/z$tech_start-1);z$total_growth<-100*(z$employed_end/z$employed_start-1);z}
z<-changes(s,2018,2024)
periods<-list(c(2018,2019),c(2019,2021),c(2021,2024),c(2018,2024))
stats<-do.call(rbind,lapply(periods,function(p){v<-changes(s,p[1],p[2]);data.frame(period=paste(p,collapse='-'),n=nrow(v),unemployment_r=cor(v$tech_change,v$unemployment_change),epr_r=cor(v$tech_change,v$epr_change))}))
write.csv(z,'results/state-changes.csv',row.names=FALSE);write.csv(stats,'results/period-correlations.csv',row.names=FALSE);write.csv(changes(bay,2018,2024,'county'),'results/bay-changes.csv',row.names=FALSE)
# Each state has equal weight. Published ACS estimates already incorporate survey weights.
# Percentage-point changes apply to rates; percent growth applies to counts. No causal inference.
theme_set(theme_minimal(base_size=12)+theme(panel.grid.minor=element_blank(),plot.background=element_rect(fill='#fbf9f3',colour=NA),plot.title=element_text(face='bold',colour='#173f3b'),legend.position='bottom'))
x<-subset(s,year %in% c(2018,2024));x$year<-factor(x$year)
p1<-ggplot(x,aes(tech_share,unemployment))+geom_point(colour='#21665c',alpha=.6,size=2)+geom_smooth(method='lm',se=FALSE,colour='#b77839',linewidth=.7)+geom_text(data=subset(x,state==6),aes(label='California'),vjust=-.8,hjust=1,size=3)+facet_wrap(~year)+labs(title='1. Are tech-heavy states better places to find work?',x='Computer and mathematical workers / employed residents (%)',y='Unemployment rate (%)',caption='ACS 1-year estimates | 50 states, excluding DC | Lines are descriptive linear fits.')
long<-rbind(data.frame(z,outcome='Unemployment rate',change=z$unemployment_change),data.frame(z,outcome='Employment / population',change=z$epr_change))
p2<-ggplot(long,aes(tech_change,change))+geom_hline(yintercept=0,colour='grey65')+geom_vline(xintercept=0,colour='grey65')+geom_point(colour='#21665c',size=2,alpha=.75)+geom_smooth(method='lm',se=FALSE,colour='#b77839',linewidth=.7)+geom_text(data=subset(long,state==6),aes(label='California'),vjust=-1,hjust=1,size=3)+facet_wrap(~outcome,scales='free_y')+labs(title='2. Did tech expansion accompany better employment outcomes?',subtitle='2018 to 2024 | Changes within each state',x='Change in tech employment share (percentage points)',y='Change in outcome (percentage points)',caption='Lower unemployment and higher employment/population indicate improvement. Association is not causation.')
q<-subset(stats,period!='2018-2024');q<-rbind(data.frame(period=q$period,outcome='Unemployment change',r=q$unemployment_r),data.frame(period=q$period,outcome='Employment/population change',r=q$epr_r))
p3<-ggplot(q,aes(r,period,colour=outcome))+geom_vline(xintercept=0,colour='grey60')+geom_point(size=3,position=position_dodge(width=.35))+scale_x_continuous(limits=c(-1,1))+scale_colour_manual(values=c('#21665c','#b77839'))+labs(title='3. Does the relationship hold across periods?',x='Correlation with change in tech share (Pearson r)',y=NULL,colour=NULL,caption='Each correlation uses 50 states. 2019-2021 spans the pandemic; standard 2020 ACS estimates are unavailable.')
b<-rbind(data.frame(year=bay$year,area=sub(', California','',bay$NAME),tech_share=bay$tech_share,unemployment=bay$unemployment),data.frame(year=subset(d,state==6)$year,area='California',tech_share=subset(d,state==6)$tech_share,unemployment=subset(d,state==6)$unemployment))
b<-rbind(data.frame(year=b$year,area=b$area,metric='Tech share (%)',value=b$tech_share),data.frame(year=b$year,area=b$area,metric='Unemployment rate (%)',value=b$unemployment));b$segment<-ifelse(b$year<2020,'before','after')
p4<-ggplot(b,aes(year,value,colour=area,group=interaction(area,segment)))+geom_line(linewidth=.8)+geom_point(size=2)+facet_wrap(~metric,scales='free_y')+scale_x_continuous(breaks=c(2018,2020,2022,2024))+scale_colour_manual(values=c('#737c89','#21665c','#b77839'))+labs(title='4. Two Bay Area core counties in the national story',x=NULL,y=NULL,colour=NULL,caption='Residence-based estimates; these counties do not represent the full nine-county Bay Area.\nNo standard annual ACS estimate for 2020; lines break across the gap.')
for(i in 1:4)ggsave(paste0('results/figure',i,'.png'),get(paste0('p',i)),width=11,height=6,dpi=180)
writeLines(capture.output(sessionInfo()),'results/session-info.txt')
print(stats);print(z[z$state==6,c('tech_share_start','tech_share_end','unemployment_change','epr_change','tech_growth','total_growth')]);cat('States gaining tech share:',sum(z$tech_change>0),'\n');cat('Cross-sectional r:',cor(subset(s,year==2018)$tech_share,subset(s,year==2018)$unemployment),cor(subset(s,year==2024)$tech_share,subset(s,year==2024)$unemployment),'\n');cat('All tech counts grow:',all(z$tech_growth[z$tech_change>0]>0),'\n')
